name: Gradle build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create file google-services.json
      run: cat /home/runner/work/motoconnect-mobile/motoconnect-mobile/app/google-services.json | base64
    - name: Putting data google-services.json
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > /home/runner/work/motoconnect-mobile/motoconnect-mobile/app/google-services.json

    - name: Create file local.properties
      run: cat /home/runner/work/motoconnect-mobile/motoconnect-mobile/app/local.properties | base64
    - name: Putting data local.properties
      env:
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: |
        echo "MAPS_API_KEY=$MAPS_API_KEY" > ./local.properties
        echo "WEATHER_API_KEY=$WEATHER_API_KEY" >> ./local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
